type int = number;

namespace SplitTime {
    export var location = {
        images: "images/",
        audio: "audio/",
        levels: "levels/"
    };

    export var process = "hold"; //Input of master setInterval switch-case
    
    export var SCREENX = 640;
    export var SCREENY = 360;
    
    export var FPS = 60;
    export var msPerFrame = (1/SplitTime.FPS)*1000;

    // Generated by Grunt
    export var _GAME_DATA: {
        levels: SplitTime.level.FileData[],
        musicFiles: string[],
        preloadedImageFiles: string[],
        soundEffectFiles: string[]
    };
}
