export const LEVEL_DIRECTORY = "levels"
export const COLLAGE_DIRECTORY = "collage"
export const IMAGE_DIRECTORY = "images"
export const PRELOADED_IMAGE_DIRECTORY = IMAGE_DIRECTORY + "preloaded"
export const AUDIO_DIRECTORY = "audio"
export const MUSIC_DIRECTORY = AUDIO_DIRECTORY + "music"
export const SOUND_EFFECT_DIRECTORY = AUDIO_DIRECTORY + "fx"
export const TASK_DATA_GEN = 'generate-data-js'
export const TASK_DECL_GEN = 'generate-index-d-ts'
