export {};
// renderClock(context: GenericCanvasRenderingContext2D) {
//     context.drawImage(splitTime.image.get("clock.png"), splitTime.SCREENX - 140, 0);
//     context.lineWidth = 1;
//     context.strokeStyle = "#DDDDDD";
//     var hand = Math.PI / 2 - (2 * (this.clockSeconds / 60) * Math.PI);
//     context.beginPath();
//     context.moveTo(splitTime.SCREENX - 70, 70);
//     context.lineTo(splitTime.SCREENX - 70 + 50 * Math.cos(hand), 70 - 50 * Math.sin(hand));
//     context.stroke();
//     context.lineWidth = 2;
//     context.strokeStyle = "#000000";
//     hand = Math.PI / 2 - (2 * (this.clockMinutes / 60) * Math.PI);
//     context.beginPath();
//     context.moveTo(splitTime.SCREENX - 70, 70);
//     context.lineTo(splitTime.SCREENX - 70 + 50 * Math.cos(hand), 70 - 50 * Math.sin(hand));
//     context.stroke();
//     context.strokeStyle = "#EE0000";
//     context.lineWidth = 3;
//     hand = Math.PI / 2 - (2 * (this.clockHours / 12) * Math.PI);
//     context.beginPath();
//     context.moveTo(splitTime.SCREENX - 70, 70);
//     context.lineTo(splitTime.SCREENX - 70 + 50 * Math.cos(hand), 70 - 50 * Math.sin(hand));
//     context.stroke();
// };
